### ISSUE TITLE
[EPIC] Setup dbt-adapter packaging and release process

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-adapters#2]
We need to get dbt-adapter up and running! 

```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/11
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/12
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/13
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/14
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/16
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/9
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/17
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/10
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/22
- [ ] https://github.com/dbt-labs/dbt-adapter/pull/25
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/5
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/6
- [ ] https://github.com/dbt-labs/dbt-adapters/pull/42
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/3
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/4
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/36
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/7
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/8
- [ ] https://github.com/dbt-labs/dbt-adapters/issues/33
- [ ] Ensure unit testing feature is fully migrated (including unit/functional tests)
```
