### ISSUE TITLE
[Feature] Adapters Model Configuration Snowplow Tracking

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-adapters#301]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-adapters functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Since it's inception dbt Core has not given a great deal of thought to adapter specific telemetry. This poses a challenge for us in tracking feature adoption and assessing the impact/risk of making changes. 

What we propose is to expose a new method in the base adapter that accepts a `RelationConfig` and returns an object that conforms to`RelationTrackingInfo` protocol (tentative name) which details the standard set of fields we want to know about _all_ relations as well as the adapter specific information relevant to that relation. By default this method would return just the basic fields and individual adapters could override to return more specific information. 

This method would be invoked [here](https://github.com/dbt-labs/dbt-core/blob/1d3d315249c81dbca70452e5a14fbfd0edad6b2a/core/dbt/task/run.py#L118C5-L118C30) by dbt-core so this does not require direct integration with snowplow itself. 

Next step is to flesh the design of this out and implement a rough proof-of-concept.

**Comment by VersusFacit** [comment]
Gathering alignment from Michelle / Andrew as part of this work.
