### ISSUE TITLE
[SPIKE] Investigate state of transactions

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-adapters#636]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Several issues already exist that even today, transactions are not working in dbt-redshift as they should

Similar to https://github.com/dbt-labs/dbt-adapters/issues/347 but only for dbt-redshift. Less future looking, but rather backward looking. How can we get back to a previous state?

#### questions
- Will https://github.com/aws/amazon-redshift-python-driver/issues/162 solve our problems, or is there more to do?
- how does the [`autocommit` parameter](https://docs.getdbt.com/docs/core/connect-data-platform/redshift-setup#autocommit-parameter) introduced in dbt-labs/dbt-core#475 affect transaction behavior?
- is there a way to expose `redshift_connector`'s `.commit()` method to users in jinja land instaed?

```[tasklist]
### Transaction-related open issues
- [ ] dbt-labs/dbt-core#521 
- [ ] dbt-labs/dbt-core#663
- [ ] dbt-labs/dbt-core#693
- [ ] dbt-labs/dbt-core#741
- [ ] dbt-labs/dbt-core#766
```
